files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%two_letters_code%/strings.xml
  - source: /desktop/src/main/resources/lang/en.json
    translation: /desktop/src/main/resources/lang/%two_letters_code%.json
