name: Perform Unit tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up JDK 15
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '15'
          java-package: jdk
          cache: 'gradle'

      - name: Prepare Gradle secure file
        run: |
          echo 'SIGNING_KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}' >> local.properties
          echo 'SIGNING_KEY_ALIAS=${{ secrets.KEYSTORE_USERNAME }}' >> local.properties
          echo 'SIGNING_KEY_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}' >> local.properties
          echo 'host=${{ secrets.HOST }}' >> local.properties
          echo 'woo.consumer_key=${{ secrets.WOO_CONSUMER_KEY }}' >> local.properties
          echo 'woo.consumer_secret=${{ secrets.WOO_CONSUMER_SECRET }}' >> local.properties
          echo 'db.hostname=${{ secrets.DB_HOSTNAME }}' >> local.properties
          echo 'db.port=${{ secrets.DB_PORT }}' >> local.properties
          echo 'db.database=${{ secrets.DB_DATABASE }}' >> local.properties
          echo 'db.username=${{ secrets.DB_USERNAME }}' >> local.properties
          echo 'db.password=${{ secrets.DB_PASSWORD }}' >> local.properties
          echo 'SENTRY_DSN=${{ secrets.SENTRY_DSN }}' >> local.properties
          echo 'AES_KEY=${{ secrets.AES_KEY }}' >> local.properties
          echo 'AES_SALT=${{ secrets.AES_SALT }}' >> local.properties
          echo 'AES_IV=${{ secrets.AES_IV }}' >> local.properties

      - name: Run unit tests
        id: unit_tests
        run: ./gradlew test --stacktrace
